#consul服务端口号
server:
  port: 8006

spring:
  cloud:
  application:
    name: consul-provider-payment
  #consul注册中心地址
  consul:
    host: localhost
    port: 8500
    discovery:
    service-name: ${spring.application.name}
    #hostname: 127.0.0.1
